### ISSUE TITLE
Is this in development?

### ISSUE THREAD

**Issue by seppi91** [segator/Ownline#1]
Hi,
I've found your project via hubic forums. I'm very interested in your kind of software and would like to know what's the current state of this.

**Comment by segator** [comment]
Hi.

Yes the project is going on, but slowly because I have lot of work in the
office and I can't develop it as quick as I would want it.

Now the project have all operations that Hubic allow. Upload(short and
large)  download, copy, move, mkdir... and it's working fine, see and
example


But all user operations aren't implemented yet(all this operations only can
change through BBDD directly with queries)

You can see and example of public share link
https://cloud.segator.es/share/ID_96c63d0997119724ecbeb3ccadd24686

and a picture of my main menu
https://cloud.segator.es/share/ID_a540bc96e42a835a135223299efd30b4



Kind Regards,

Isaac

2015-05-16 8:31 GMT+02:00 seppi91 <notifications@github.com>:

**Comment by seppi91** [comment]
Thank you for your helpful reply Isaac. This looks like a really nice piece of software, I'm sure you've put a lot of effort into it.
Could you tell me what speed I could expect from your implementation to owncloud?

As I was looking around the last few days for solutions like this I also found:
https://pyd.io/f/topic/hubic-plugin/
Maybe it's also an interesting alternative for you, or maybe you can merge your KnowHow and Code with the dev of this plugin ;)

**Comment by segator** [comment]
Hi again,

I have been trying pydio and hubic pydio plugin but it has the same problem
as owncloud + hubic plugin.

When you try to download a file from hubic through plugin, this plugin
download the complete file and after it finishes, it sends you the file.
This means that you need to download the file two times.
The first time hubic to your pydio server
The second time pydio server to you.

My application use buffers and create a direct pipe link between hubic
server and you.
This means that you can download/upload directly, but the problem with this
is that my server generates double traffic.

I invite you to try the pydio plugin and compare it with my application.
Send me an email with an user and an password that you want, and I will
create an account for you.

Bye

2015-05-16 11:54 GMT+02:00 seppi91 <notifications@github.com>:

**Comment by seppi91** [comment]
I sent my data via hubic forums account.

Regards
